/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homepage;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Hossam Aladin
 */
public class Lecture_Mange_Table extends javax.swing.JFrame {

    Connection con;
    DefaultTableModel dtm;
    ManageCourse mc = new ManageCourse();

    private void settable() {

        dtm = (DefaultTableModel) tbl_show.getModel();
    }

    /**
     * Creates new form Lecture_Mange_Table
     */
    public Lecture_Mange_Table() {
        
        initComponents();
         this.setLocationRelativeTo(null);
        dtm = new DefaultTableModel();
        //dtm.addColumn("Course name");

        //dtm =(DefaultTableModel)tbl_show.getModel(); 
        dtm.addColumn("id");
        dtm.addColumn("course_name");
        dtm.addColumn("hours");
        dtm.addColumn("Lecture Number");
        dtm.addColumn("Assignment Number ");

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=learning;encrypt=true;trustServerCertificate=true;", "sa", "123");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addCourse.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillTableModel();
    }

    private void fillTableModel() {
        try {
            PreparedStatement stmt = con.prepareStatement("select course.id,course.course_name,course.hours,lecture.lecture_number,lecture.ass_number from course inner join lecture on course.id = lecture.id");
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getInt(3), rs.getInt(4), rs.getInt(5)});
            }
            tbl_show.setModel(dtm);
        } catch (SQLException ex) {
            Logger.getLogger(ManageCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        txtAssignmentNo1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLectureNo = new javax.swing.JTextField();
        BTNADD = new javax.swing.JButton();
        BTNDELETE = new javax.swing.JButton();
        BTNUPDATE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_show = new javax.swing.JTable();
        txtAssignmentNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        back_home_button = new javax.swing.JButton();

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        txtAssignmentNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAssignmentNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignmentNo1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(184, 216, 216));

        jLabel1.setBackground(new java.awt.Color(184, 216, 216));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Lecture Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Assignment Number");

        txtLectureNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLectureNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLectureNoActionPerformed(evt);
            }
        });

        BTNADD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNADD.setText("ADD");
        BTNADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNADDActionPerformed(evt);
            }
        });

        BTNDELETE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNDELETE.setText("DELETE");
        BTNDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDELETEActionPerformed(evt);
            }
        });

        BTNUPDATE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNUPDATE.setText("UPDATE");
        BTNUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUPDATEActionPerformed(evt);
            }
        });

        tbl_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Course name", "Hours", "Lecture number", "Assignment number"
            }
        ));
        tbl_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_showMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_show);

        txtAssignmentNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAssignmentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignmentNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        jPanel2.setBackground(new java.awt.Color(79, 99, 103));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lecture");

        backButton.setBackground(new java.awt.Color(79, 99, 103));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepage/back-arrow.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        back_home_button.setBackground(new java.awt.Color(79, 99, 103));
        back_home_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepage/home2.png"))); // NOI18N
        back_home_button.setBorder(null);
        back_home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_home_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back_home_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(back_home_button)
                            .addComponent(backButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTNADD)
                                .addGap(18, 18, 18)
                                .addComponent(BTNDELETE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLectureNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAssignmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNUPDATE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtLectureNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNADD)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BTNDELETE)
                                        .addComponent(BTNUPDATE))))
                            .addComponent(txtAssignmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtAssignmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignmentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignmentNoActionPerformed


    private void BTNADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNADDActionPerformed

        //THE CODE FOR ADD BUTTON (INSERT DATA TO THE TABLE)
        if (!txtLectureNo.getText().isEmpty() && !txtAssignmentNo.getText().isEmpty()) {
            try {
                int lec_text = Integer.parseInt(txtLectureNo.getText());
                int ass_text = Integer.parseInt(txtAssignmentNo.getText());
                int Id_text = Integer.parseInt(id_text.getText());
                PreparedStatement stmt = con.prepareStatement("insert into lecture(lecture.id,lecture_number,ass_number) values(?,?,?)");
                stmt.setInt(1, Id_text);
                stmt.setInt(2, lec_text);
                stmt.setInt(3, ass_text);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Added successfully");
                Lecture_Mange_Table lmt = new Lecture_Mange_Table();
                lmt.show();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Lecture_Mange_Table.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BTNADDActionPerformed

    private void txtLectureNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLectureNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLectureNoActionPerformed

    private void BTNDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDELETEActionPerformed

        if (!txtLectureNo.getText().isEmpty() && !txtAssignmentNo.getText().isEmpty()) {
            try {
               
                int Id_text = Integer.parseInt(id_text.getText());
                PreparedStatement stmt = con.prepareStatement("delete from lecture where lecture.id=?");
                stmt.setInt(1, Id_text);
                
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted successfully");
                Lecture_Mange_Table lmt = new Lecture_Mange_Table();
                lmt.show();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Lecture_Mange_Table.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_BTNDELETEActionPerformed

//    private void clearText() {
//
//             txtcourse_id.setText("");
//             txtLectureNo.setText("");
//             txtAssignmentNo.setText("");
//             txtcourse_id.requestFocus();  
//    }
//       int CurrentRow;
    private void BTNUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUPDATEActionPerformed

        if (!txtLectureNo.getText().isEmpty() && !txtAssignmentNo.getText().isEmpty()) {
            try {
                int lec_text = Integer.parseInt(txtLectureNo.getText());
                int ass_text = Integer.parseInt(txtAssignmentNo.getText());
                int Id_text = Integer.parseInt(id_text.getText());
                PreparedStatement stmt = con.prepareStatement("update  lecture set  lecture_number = ? ,ass_number = ? where lecture.id = ?");
                stmt.setInt(3, Id_text);
                stmt.setInt(1, lec_text);
                stmt.setInt(2, ass_text);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "updated successfully");
                Lecture_Mange_Table lmt = new Lecture_Mange_Table();
                lmt.show();
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Lecture_Mange_Table.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_BTNUPDATEActionPerformed

    private void txtAssignmentNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignmentNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignmentNo1ActionPerformed

    private void tbl_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_showMouseClicked
        // TODO add your handling code here:
        id_text.setText(tbl_show.getValueAt(tbl_show.getSelectedRow(), 0).toString());
        txtLectureNo.setText(tbl_show.getValueAt(tbl_show.getSelectedRow(), 3).toString());
        txtAssignmentNo.setText(tbl_show.getValueAt(tbl_show.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tbl_showMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        courses c = new courses();
        c.show();
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void back_home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_home_buttonActionPerformed
        // TODO add your handling code here:
        home_page backHome = new home_page();
        backHome.show();
        dispose();
    }//GEN-LAST:event_back_home_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecture_Mange_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecture_Mange_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecture_Mange_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecture_Mange_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Lecture_Mange_Table().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNADD;
    private javax.swing.JButton BTNDELETE;
    private javax.swing.JButton BTNUPDATE;
    private javax.swing.JButton backButton;
    private javax.swing.JButton back_home_button;
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tbl_show;
    private javax.swing.JTextField txtAssignmentNo;
    private javax.swing.JTextField txtAssignmentNo1;
    private javax.swing.JTextField txtLectureNo;
    // End of variables declaration//GEN-END:variables

}
